[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "netbox-zabbix2-traffic"
version = "1.0.0"
description = "A NetBox plugin to display dynamic Zabbix traffic graphs and metrics on interface pages (v2)"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Antigravity", email = "antigravity@google.com" }
]
classifiers = [
    "Framework :: Django",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "requests"
]

[tool.setuptools.packages.find]
include = ["netbox_zabbix2_traffic*"]
